config/routes.rb
# frozen_string_literal: true

# Copyright 2019 Andrew Esler (ajesler)
# Copyright 2019 Matthew B. Gray
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Rails.application.routes.draw do
  root to: "menu#index"

  devise_for :users
  get "/login/:email/:key", to: "user_tokens#kansa_login_link", email: /[^\/]+/, key: /[^\/]+/
  resources :user_tokens, only: [:new, :show, :create], id: /[^\/]+/ do
    get :logout, on: :collection
  end

  resources :menu
  resources :charges
  resources :themes
  resources :purchases

  mount(LetterOpenerWeb::Engine, at: "/letter_opener") if Rails.env.development?
end

app/controllers/menu_controller.rb
# frozen_string_literal: true

# Copyright 2019 Matthew B. Gray
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

class MenuController < ApplicationController
  def index
  end
end

app/views/menu/index.html.erb
<%#
  Copyright 2019 Matthew B. Gray

  Permission is hereby granted, free of charge, to any person obtaining a copy of
  this software and associated documentation files (the "Software"), to deal in
  the Software without restriction, including without limitation the rights to
  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
  the Software, and to permit persons to whom the Software is furnished to do so,
  subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
  FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
  COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
  IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
  CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
%>

<nav class="l-section">
  <h1>Menu</h1>
  <div class="row">
    <div class="col-12 col-md-12">
      <div class="l-panel">
        <h2>Account Actions</h2>
        <% if current_user.present? %>
          <%= link_to("Logout #{current_user.email}", logout_user_tokens_path) %>
        <% else %>
          <%= render template: "user_tokens/new" %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-12 col-md-12">
      <div class="l-panel">
        <h2>Links</h2>
        <ul>
          <li><%= link_to "Purchase Membership", new_purchase_path %></li>
          <li><%= link_to "Review Memberships", purchases_path %></li>
          <li>Suggest for our Programme (coming soon)</li>
          <li>Volunteering (coming soon)</li>
          <li>Plan my trip(coming soon)</li>
        </ul>
      </div>
    </div>
  </div>
</nav>